GabrielBonatto_TesteGraff_Leilao/Models/Lance.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GabrielBonatto_TesteGraff_Leilao.Models
{
  public class Lance
  {
    public int Id { get; set; }
    public decimal Valor { get; set; }
    public int ProdutoId { get; set; }
    public int PessoaId { get; set; }
  }
}

GabrielBonatto_TesteGraff_Leilao/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GabrielBonatto_TesteGraff_Leilao.Models
{
  public class Pessoa
  {
    public int Id { get; set; }
    [Required(ErrorMessage = "O campo nome é obrigatório!")]
    public string Nome { get; set; }
    public int Idade { get; set; }
  }
}

GabrielBonatto_TesteGraff_Leilao/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GabrielBonatto_TesteGraff_Leilao.Models
{
  public class Produto
  {
    public int Id { get; set; }
    [Required(ErrorMessage = "O campo nome é obrigatório!")]
    public string Nome { get; set; }
    [Required(ErrorMessage = "O campo Valor é obrigatório!")]
    public decimal Valor { get; set; }
  }
}

GabrielBonatto_TesteGraff_Leilao/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GabrielBonatto_TesteGraff_Leilao.Controllers
{
  public class HomeController : Controller
  {
    public ActionResult Index() => View();
    public ActionResult CadPessoa() => View();
    public ActionResult CadProduto() => View();
  }
}

GabrielBonatto_TesteGraff_Leilao/Controllers/LanceController.cs
using GabrielBonatto_TesteGraff_Leilao.DTO;
using GabrielBonatto_TesteGraff_Leilao.Models;
using GabrielBonatto_TesteGraff_Leilao.Repository;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GabrielBonatto_TesteGraff_Leilao.Controllers
{
  public class LanceController : Controller
  {
    private LanceRepository repository = new LanceRepository();
    private PessoaRepository repositoryPessoa = new PessoaRepository();
    private ProdutoRepository repositoryProduto = new ProdutoRepository();
    public ActionResult IndexLance(string filtro)
    {
      ViewData["lstPessoa"] = repositoryPessoa.GetAll();
      ViewData["lstProduto"] = repositoryProduto.GetAll();

      return View(repository.GetAll(filtro));
    }

    public ActionResult CadLance()
    {
      ViewBag.PessoaId = new SelectList(
        repositoryPessoa.GetAll(),
        "Id",
        "Nome"
      );

      ViewBag.ProdutoId = new SelectList(
        repositoryProduto.GetAll(),
        "Id",
        "Nome"
      );

      return View();
    }

    [HttpPost]
    public ActionResult CadLance(LanceGridDTO lanceDTO)
    {
      var lance = new Lance
      {
        PessoaId = lanceDTO.PessoaId,
        ProdutoId = lanceDTO.ProdutoId,
        Valor = lanceDTO.Valor,
      };
      var lstLance = repository.GetAllByProdutoId(lance.ProdutoId);
      if(lstLance.Count > 0)
      {
        foreach (var l in lstLance) { 
          if(l.Valor >= lance.Valor)
          {
            ModelState.AddModelError("Valor", "Existe outro lance igual ou maior com valor de: R$" + l.Valor.ToString());
            return CadLance();
          }
        }
      }

      if (ModelState.IsValid)
      {
        repository.Save(lance);
        return RedirectToAction("IndexLance");
      }
      else
      {
        return View(lance);
      }
    }

    [HttpPost]
    public ActionResult Delete(int id)
    {
      repository.DeleteById(id);
      return Json(repository.GetAll(""));
    }
  }
}

GabrielBonatto_TesteGraff_Leilao/Controllers/PessoaController.cs
using GabrielBonatto_TesteGraff_Leilao.Models;
using GabrielBonatto_TesteGraff_Leilao.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GabrielBonatto_TesteGraff_Leilao.Controllers
{
  public class PessoaController : Controller
  {
    private PessoaRepository repository = new PessoaRepository();

    public ActionResult IndexPessoa()
    {
      return View(repository.GetAll());
    }

    public ActionResult CadPessoa()
    {
      return View();
    }

    [HttpPost]
    public ActionResult CadPessoa(Pessoa pessoa)
    {
      if (ModelState.IsValid)
      {
        repository.Save(pessoa);
        return RedirectToAction("IndexPessoa");
      }
      else
      {
        return View(pessoa);
      }
    }

    public ActionResult CadPessoaAlterar(int id)
    {
      var pessoa = repository.GetById(id);

      if (pessoa == null)
      {
        return HttpNotFound();
      }

      return View(pessoa);
    }

    [HttpPost]
    public ActionResult Edit(Pessoa pessoa)
    {
      if (ModelState.IsValid)
      {
        repository.Update(pessoa);
        return RedirectToAction("IndexPessoa");
      }
      else
      {
        return View(pessoa);
      }
    }

    [HttpPost]
    public ActionResult Delete(int id)
    {
      repository.DeleteById(id);
      return Json(repository.GetAll());
    }
  }
}

GabrielBonatto_TesteGraff_Leilao/Controllers/ProdutoController.cs
using GabrielBonatto_TesteGraff_Leilao.Models;
using GabrielBonatto_TesteGraff_Leilao.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GabrielBonatto_TesteGraff_Leilao.Controllers
{
  public class ProdutoController : Controller
  {
    private ProdutoRepository repository = new ProdutoRepository();
    public ActionResult IndexProduto()
    {
      return View(repository.GetAll());
    }

    public ActionResult CadProduto()
    {
      return View();
    }

    [HttpPost]
    public ActionResult CadProduto(Produto produto)
    {
      if (ModelState.IsValid)
      {
        repository.Save(produto);
        return RedirectToAction("IndexProduto");
      }
      else
      {
        return View(produto);
      }
    }
    public ActionResult CadProdutoAlterar(int id)
    {
      var produto = repository.GetById(id);

      if (produto == null)
      {
        return HttpNotFound();
      }

      return View(produto);
    }

    [HttpPost]
    public ActionResult Edit(Produto produto)
    {
      if (ModelState.IsValid)
      {
        repository.Update(produto);
        return RedirectToAction("IndexProduto");
      }
      else
      {
        return View(produto);
      }
    }

    [HttpPost]
    public ActionResult Delete(int id)
    {
      repository.DeleteById(id);
      return Json(repository.GetAll());
    }
  }
}

GabrielBonatto_TesteGraff_Leilao/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron text-center">
    <h1>Leilão Graff</h1>
    <p class="lead">por: Gabriel Bonatto</p>
</div>

<div class="row">
  <div class="text-center">
    <h2>Pessoas</h2>
    <p>
      Realizar o cadastro das pessoas que irão realizar as apostas.
    </p>
    <p><a class="btn btn-default" @Html.ActionLink("Pessoas","IndexPessoa","Pessoa", null, new { @class = "page-scroll" })</a></p>
  </div>
  <div class="text-center">
    <h2>Produtos</h2>
    <p>
      Realizar o cadastro dos produtos leiloados.
    </p>
    <p><a class="btn btn-default" @Html.ActionLink("Produtos","IndexProduto","Produto", null, new { @class = "page-scroll" })</a></p>
  </div>
  <div class="text-center">
    <h2>Lances</h2>
    <p>
      Cadastrar e Consultar Lances
    </p>
    <p><a class="btn btn-default" @Html.ActionLink("Lances","IndexLance","Lance", null, new { @class = "page-scroll" })</a></p>
  </div>
</div>

GabrielBonatto_TesteGraff_Leilao/Views/Lance/CadLance.cshtml
@model GabrielBonatto_TesteGraff_Leilao.DTO.LanceGridDTO

@{
  ViewBag.Title = "Cadastrar Lance";
}

<h2>Cadastrar Lance</h2>

@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4>LanceGridDTO</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Pessoas, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownList("PessoaId", null, new { @style = "width: 280px;"})
        @Html.ValidationMessageFor(model => model.PessoaId, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Produtos, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownList("ProdutoId", null, new { @style = "width: 280px;"})
        @Html.ValidationMessageFor(model => model.ProdutoId, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Salvar" class="btn btn-default" />
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink("Back to List", "Index")
</div>

GabrielBonatto_TesteGraff_Leilao/Views/Lance/IndexLance.cshtml
@model IEnumerable<GabrielBonatto_TesteGraff_Leilao.DTO.LanceGridDTO>

@{
  ViewBag.Title = "Lances";
}

<h2>Lances</h2>

<p>
  @Html.ActionLink("Adicionar Novo", "CadLance")
</p>
@using (Html.BeginForm())
{
  <p>
    Find by name: @Html.TextBox("filtro")
    <input type="submit" value="Search" />
  </p>
}
<table class="table">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.Valor)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.PessoaNome)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.ProdutoNome)
    </th>
    <th></th>
  </tr>

  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.Valor)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.PessoaNome)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.ProdutoNome)
      </td>
      <td>
        @Html.ActionLink("Edit", "CadLanceAlterar", new { id = item.Id }) |
        <button type="button" class="btn btn-link" data-item="@item.Id">Deletar</button>
      </td>
    </tr>
  }
</table>

<div>
  @Html.ActionLink("Back to Home", "Index", "Home", null, new { @class = "page-scroll" })
</div>
@section Scripts {
  <script type="text/javascript">
    $(document).ready(function () {
      $(".btn-link").click(function () {
        var id = $(this).attr('data-item');
        if (confirm("Você tem certeza que gostaria de excluir este registro?")) {
          $.ajax({
            method: "POST",
            url: "/Lance/Delete/" + id,
            success: function (data) {
              $("#tblPessoas tbody > tr").remove();
              $.each(data, function (i, lance) {
                $("#tblLance tbody").append(
                  `<tr>` +
                  `   <td>` + lance.ProdutoNome + `</td>` +
                  `   <td>` + lance.PessoaNome + `</td>` +
                  `   <td>` + lance.Valor + `</td>` +
                  `   <td>` +
                  `       <a href='/Lance/Edit/` + lance.Id + `'>Editar</a> |` +
                  `       <button type="button" class="btn btn-link" data-item=` + pessoa.Id + `>Deletar</button>` +
                  `   </td>` +
                  `</tr>`
                );
              });
            },
            error: function (data) {
              alert("Houve um erro na pesquisa.");
            }
          });
        }
      });
    });
  </script>
}

GabrielBonatto_TesteGraff_Leilao/Views/Pessoa/CadPessoa.cshtml
@model GabrielBonatto_TesteGraff_Leilao.Models.Pessoa

@{
  ViewBag.Title = "Cadastrar Pessoa";
}

<h2>Cadastrar Nova Pessoa</h2>


@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4>Pessoa</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Salvar" class="btn btn-default" />
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink("Back to List", "IndexPessoa")
</div>
<script src="~/Scripts/jquery.validate.min.js" />
<script src="~/Scripts/jquery.validate.unobtrusive.min.js" />

GabrielBonatto_TesteGraff_Leilao/Views/Pessoa/CadPessoaAlterar.cshtml
@model GabrielBonatto_TesteGraff_Leilao.Models.Pessoa

@{
  ViewBag.Title = "Alterar Pessoa";
}

<h2>Alterar Pessoa</h2>


@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4>Pessoa</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
      @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Save" class="btn btn-default" />
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink("Back to List", "IndexPessoa")
</div>
<script src="~/Scripts/jquery.validate.min.js" />
<script src="~/Scripts/jquery.validate.unobtrusive.min.js" />

GabrielBonatto_TesteGraff_Leilao/Views/Pessoa/IndexPessoa.cshtml
@model IEnumerable<GabrielBonatto_TesteGraff_Leilao.Models.Pessoa>
@{
  ViewBag.Title = "Index";
}
<h2>Index</h2>

<p>
  @Html.ActionLink("Adicionar Pessoa", "CadPessoa")
</p>
<table class="table" id="tblPessoas">
  <thead>
    <tr>
      <th>
        @Html.DisplayNameFor(model => model.Nome)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Idade)
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model)
    {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Idade)
        </td>
        <td>
          <button type="button" class="btn btn-link" data-item="@item.Id">Deletar</button>
        </td>
      </tr>
    }
  </tbody>
</table>

<div>
  @Html.ActionLink("Back to Home", "Index", "Home", null, new { @class = "page-scroll" })
</div>
@section Scripts {
  <script type="text/javascript">
    $(document).ready(function () {
      $(".btn-link").click(function () {
        var id = $(this).attr('data-item');
        if (confirm("Você tem certeza que gostaria de excluir este registro?")) {
          $.ajax({
            method: "POST",
            url: "/Pessoa/Delete/" + id,
            success: function (data) {
              $("#tblPessoas tbody > tr").remove();
              $.each(data, function (i, pessoa) {
                $("#tblPessoas tbody").append(
                  `<tr>` +
                  `   <td>` + pessoa.Nome + `</td>` +
                  `   <td>` + pessoa.Idade + `</td>` +
                  `   <td>` +
                  `       <a href='/Pessoa/Edit/` + pessoa.Id + `'>Editar</a> |` +
                  `       <button type="button" class="btn btn-link" data-item=` + pessoa.Id + `>Deletar</button>` +
                  `   </td>` +
                  `</tr>`
                );
              });
            },
            error: function (data) {
              alert("Houve um erro na pesquisa.");
            }
          });
        }
      });
    });
  </script>
}

GabrielBonatto_TesteGraff_Leilao/Views/Produto/CadProduto.cshtml
@model GabrielBonatto_TesteGraff_Leilao.Models.Produto

@{
  ViewBag.Title = "Cadstrar Produto";
}

<h2>Cadastrar Produto</h2>

@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4>Produto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Salvar" class="btn btn-default" />
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink("Back to List", "IndexProduto")
</div>

GabrielBonatto_TesteGraff_Leilao/Views/Produto/CadProdutoAlterar.cshtml
@model GabrielBonatto_TesteGraff_Leilao.Models.Produto

@{
  ViewBag.Title = "Alterar Produto";
}

<h2>Alterar Produto</h2>

@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4>Produto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
      @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Salvar" class="btn btn-default" />
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink("Back to List", "IndexProduto")
</div>

GabrielBonatto_TesteGraff_Leilao/Views/Produto/IndexProduto.cshtml
@model IEnumerable<GabrielBonatto_TesteGraff_Leilao.Models.Produto>

@{
  ViewBag.Title = "IndexProduto";
}

<h2>IndexProduto</h2>

<p>
  @Html.ActionLink("Adicionar Produto", "CadProduto")
</p>
<table class="table" id="tblProdutos">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.Nome)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Valor)
    </th>
    <th></th>
  </tr>

  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.Nome)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Valor)
      </td>
      <td>
        @Html.ActionLink("Editar", "CadProdutoAlterar", new { id = item.Id }) |
        <button type="button" class="btn btn-link" data-item="@item.Id">Deletar</button>
      </td>
    </tr>
  }

</table>

<div>
  @Html.ActionLink("Back to Home", "Index", "Home", null, new { @class = "page-scroll" })
</div>
@section Scripts {
  <script type="text/javascript">
    $(document).ready(function () {
      $(".btn-link").click(function () {
        var id = $(this).attr('data-item');
        if (confirm("Você tem certeza que gostaria de excluir este registro?")) {
          $.ajax({
            method: "POST",
            url: "/Produto/Delete/" + id,
            success: function (data) {
              $("#tblProdutos tbody > tr").remove();
              $.each(data, function (i, produto) {
                $("#tblProdutos tbody").append(
                  `<tr>` +
                  `   <td>` + produto.Nome + `</td>` +
                  `   <td>` + produto.Valor + `</td>` +
                  `   <td>` +
                  `       <a href='/Produto/Edit/` + produto.Id + `'>Editar</a> |` +
                  `       <button type="button" class="btn btn-link" data-item="` + produto.Id + `">Deletar</button>` +
                  `   </td>` +
                `</tr>`
                );
              });
            },
            error: function (data) {
              alert("Houve um erro na pesquisa.");
            }
          });
        }
      });
    });
  </script>
}

GabrielBonatto_TesteGraff_Leilao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Leilão Graff - Gabriel Bonatto</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>